    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: myapp-argo-application
      namespace: argocd
    spec:
      destination:
        server: https://kubernetes.default.svc
        namespace: myapp
      source:
        repoURL: https://github.com/basavarajgs/k8s
        targetRevision: HEAD
        path: k8s
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
